### ISSUE TITLE
release to the store

### ISSUE THREAD

**Issue by iddan** [ramya-rao-a/vscode-emmet#3]

**Comment by ramya-rao-a** [comment]
Do you mean "publish the extension to the VS Code marketplace" ?

**Comment by iddan** [comment]
yes

**Comment by ramya-rao-a** [comment]
There are a few more things we need to resolve around the replacement for built in emmet features.

Will publish soon after, definitely by end of May

**Comment by jens1o** [comment]
Is this going to be an own extension or will this be in the core next release?

**Comment by ramya-rao-a** [comment]
The plan is to have it as a built in extension.

Closing this issue as we wont be publishing emmet as an external extension
