### ISSUE TITLE
Emmet will not expand react component

### ISSUE THREAD

**Issue by sheltondong** [ramya-rao-a/vscode-emmet#7]
I don't know how to configure emmet to supports the feature that will expand react component, or there is no such functionality.
For example:
`div`+<kbd>Tab</kbd> => `<div></div>`, It works.
`Route`+<kbd>Tab</kbd> => nothing happend.

**Comment by rzhao271** [comment]
Closing as the code for the Emmet extension is now on the main repo. See https://github.com/microsoft/vscode/issues/89746
