### ISSUE TITLE
auto_id_class

### ISSUE THREAD

**Issue by franciscolourenco** [ramya-rao-a/vscode-emmet#8]
Is this feature currently supported in vscode-emmet?

https://github.com/Microsoft/vscode/issues/33592

**Comment by rzhao271** [comment]
Please check whether the functionality now works in the latest vscode (1.53.2 at this time).
If not, please file a feature request for this in the main https://github.com/microsoft/vscode repo, as this repository does not contain the current Emmet extension code.
