### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by wang-st** [ramya-rao-a/vscode-emmet#9]
- Issue Type: `Performance`
- Extension Name: `emmet`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.35.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\WangRui\vscode.emmet-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by SH2000** [comment]
same here, unstable work of built in emmet extension. extension causes high cpu load.
macOS 10.14.5, VSCode 1.35.0

**Comment by massimo-cassandro** [comment]
same issue with Code 1.41.1 on OSX

**Comment by rzhao271** [comment]
Please check whether the functionality now works in the latest vscode (1.53.2 at this time).
If not, please file an issue for this in the main https://github.com/microsoft/vscode repo, as this repository does not contain the current Emmet extension code.
